- name: Cows saying stuff
  hosts: localhost
  vars:
    ansible_connection: local

  tasks:
    - name: Install the cowsay package
      ansible.builtin.yum:
        name: cowsay
        state: present
        update_cache: true
      become: true

    - name: Run cowsay
      ansible.builtin.command: "cowsay \"Never gonna run around and desert you\""
      register: cowsay_out

    - name: Display cowsay results
      ansible.builtin.debug:
        var: cowsay_out.stdout_lines
